# Generated by Django 6.0.3 on 2026-05-22 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_atualizacao', models.DateField(auto_now=True, verbose_name='Última Atualização')),
                ('problemas_cardiacos', models.BooleanField(default=False, verbose_name='Problemas Cardíacos')),
                ('cirurgias_recentes', models.BooleanField(default=False, verbose_name='Cirurgias Recentes')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('restricoes_fisicas', models.TextField(blank=True, null=True, verbose_name='Restrições Físicas')),
                ('medicamentos_em_uso', models.TextField(blank=True, null=True, verbose_name='Medicamentos em Uso')),
                ('pressao_arterial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pressão Arterial')),
                ('diabetes', models.BooleanField(default=False, verbose_name='Diabetes')),
                ('fumante', models.BooleanField(default=False, verbose_name='Fumante')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
                'ordering': ['-ultima_atualizacao'],
            },
        ),
    ]
